<?php

    $AnalysisDetails = array( 0=>array("Assigned_Date"=>"11/04/2019",
                                       "Assessment_Date"=>"11/03/2019",
                                       "Assessments"=>array(0=>array("Color"=>"#00bfff",
                                                                     "Text"=>"Assessment 11/03/2019 (age 2 years, 11 months)")),
                                       "Normative_Data"=>"2 years",
                                       "Output_Options"=>"Table analysis of single assesment",
                                       "Graphs_with_Total_Items_Scale"=>array(0=>"Include Section Graphs",
                                                                              1=>"Include Categories Graphs"),
                                       "Graphs_with_Total_Scores_Scale"=>array(0=>"Include Section Graphs",
                                                                               1=>"Include Categories Graphs"),
                                       "Graphs_with_Percentage_Scale"=>array(0=>"Include Section Graphs",
                                                                             1=> "Include Categories Graphs"),
                                       "Section_Analysis"=>array(0=>"Basic Language and Learner Skills Section (A-P)",
                                                                 1=>"Language Skills (C,E,F,G,H,I,J)",
                                                                 2=>"Academic Skills Section (Q-T)",
                                                                 3=>"Self-Help Skills Section (U-X)",
                                                                 4=>"Motor Skill Section (Y-Z)",
                                                                 5=>"Total ABLLS-R (A-Z)"),
                                       "Category_Analysis"=>array(  0=>"A. Cooperation and Reinfocer Effectiveness",
                                                                    1=>"B. Visual Performance",
                                                                    2=>"C. Receptive Language",
                                                                    3=>"D. Motor lmitation",
                                                                    4=>"E. Vocal lmitation",
                                                                    5=>"F. Requests",
                                                                    6=>"G. Labeling",
                                                                    7=>"H. Intraverbals",
                                                                    8=>"I. Spontaneous Vocalizations",
                                                                    9=>"J. Syntax and Grammar",
                                                                   10=>"K. Play and Leisure Skills",
                                                                   11=>"L. Social Interactions",
                                                                   12=>"M. Group Instruction",
                                                                   13=>"N. Follow Classroom Routines",
                                                                   14=>"P. Generalized Responding",
                                                                   15=>"Q. Reading Skills",
                                                                   16=>"R. Math Skills",
                                                                   17=>"S. Writing Skills",
                                                                   18=>"T. Spelling",
                                                                   19=>"U. Dressing Skills",
                                                                   20=>"V. Eating Skills",
                                                                   21=>"W. Grooming Skills",
                                                                   22=>"X. Toileting Skills",
                                                                   23=>"Y. Gross Motor Skills",
                                                                   24=>"Z. Fine Motor Skills")
                                       ));
    $Chart = array( 0=>array("ID"=>"Chart0",
                             "Title"=>"Basic Language and Learner Skills Section",
                             "Value_Color"=>array(0=>"rgba(119, 247, 119, 0.5)",
                                                  1=>"rgba(154, 145, 138, 0.5)",
                                                  2=>"rgba(154, 145, 138, 0.5)",
                                                  3=>"rgba(154, 145, 138, 0.5)",
                                                  4=>"rgba(154, 145, 138, 0.5)",
                                                  5=>"rgba(86, 104, 120, 0.5)"),
                             "Total_Value_Color"=>array(0=>"rgba(119, 247, 119, 1)",
                                                        1=>"rgba(154, 145, 138, 1)",
                                                        2=>"rgba(154, 145, 138, 1)",
                                                        3=>"rgba(154, 145, 138, 1)",
                                                        4=>"rgba(154, 145, 138, 1)",
                                                        5=>"rgba(86, 104, 120, 1)"),
                             "Value"=>array(0=>"100",
                                            1=>"70",
                                            2=>"70",
                                            3=>"70",
                                            4=>"70",
                                            5=>"0"),
                             "Total_Value"=>array(0=>"150",
                                                  1=>"100",
                                                  2=>"100",
                                                  3=>"100",
                                                  4=>"100",
                                                  5=>"220")),
                     1=>array("ID"=>"Chart1",
                             "Title"=>"Language Skills",
                             "Value_Color"=>array(0=>"rgba(119, 247, 119, 0.5)",
                                                  1=>"rgba(154, 145, 138, 0.5)",
                                                  2=>"rgba(154, 145, 138, 0.5)",
                                                  3=>"rgba(154, 145, 138, 0.5)",
                                                  4=>"rgba(154, 145, 138, 0.5)",
                                                  5=>"rgba(86, 104, 120, 0.5)"),
                             "Total_Value_Color"=>array(0=>"rgba(119, 247, 119, 1)",
                                                        1=>"rgba(154, 145, 138, 1)",
                                                        2=>"rgba(154, 145, 138, 1)",
                                                        3=>"rgba(154, 145, 138, 1)",
                                                        4=>"rgba(154, 145, 138, 1)",
                                                        5=>"rgba(86, 104, 120, 1)"),
                             "Value"=>array(0=>"120",
                                            1=>"40",
                                            2=>"40",
                                            3=>"40",
                                            4=>"40",
                                            5=>"0"),
                             "Total_Value"=>array(0=>"150",
                                                  1=>"100",
                                                  2=>"100",
                                                  3=>"100",
                                                  4=>"100",
                                                  5=>"220")),
                     2=>array("ID"=>"Chart2",
                             "Title"=>"Academic Skills Section",
                             "Value_Color"=>array(0=>"rgba(119, 247, 119, 0.5)",
                                                  1=>"rgba(154, 145, 138, 0.5)",
                                                  2=>"rgba(154, 145, 138, 0.5)",
                                                  3=>"rgba(154, 145, 138, 0.5)",
                                                  4=>"rgba(154, 145, 138, 0.5)",
                                                  5=>"rgba(86, 104, 120, 0.5)"),
                             "Total_Value_Color"=>array(0=>"rgba(119, 247, 119, 1)",
                                                        1=>"rgba(154, 145, 138, 1)",
                                                        2=>"rgba(154, 145, 138, 1)",
                                                        3=>"rgba(154, 145, 138, 1)",
                                                        4=>"rgba(154, 145, 138, 1)",
                                                        5=>"rgba(86, 104, 120, 1)"),
                             "Value"=>array(0=>"50",
                                            1=>"10",
                                            2=>"10",
                                            3=>"10",
                                            4=>"10",
                                            5=>"0"),
                             "Total_Value"=>array(0=>"150",
                                                  1=>"100",
                                                  2=>"100",
                                                  3=>"100",
                                                  4=>"100",
                                                  5=>"220")),
                     3=>array("ID"=>"Chart3",
                             "Title"=>"Self-Help Skills Section",
                             "Value_Color"=>array(0=>"rgba(119, 247, 119, 0.5)",
                                                  1=>"rgba(154, 145, 138, 0.5)",
                                                  2=>"rgba(154, 145, 138, 0.5)",
                                                  3=>"rgba(154, 145, 138, 0.5)",
                                                  4=>"rgba(154, 145, 138, 0.5)",
                                                  5=>"rgba(86, 104, 120, 0.5)"),
                             "Total_Value_Color"=>array(0=>"rgba(119, 247, 119, 1)",
                                                        1=>"rgba(154, 145, 138, 1)",
                                                        2=>"rgba(154, 145, 138, 1)",
                                                        3=>"rgba(154, 145, 138, 1)",
                                                        4=>"rgba(154, 145, 138, 1)",
                                                        5=>"rgba(86, 104, 120, 1)"),
                             "Value"=>array(0=>"50",
                                            1=>"10",
                                            2=>"10",
                                            3=>"10",
                                            4=>"10",
                                            5=>"0"),
                             "Total_Value"=>array(0=>"150",
                                                  1=>"100",
                                                  2=>"100",
                                                  3=>"100",
                                                  4=>"100",
                                                  5=>"220")),
                     4=>array("ID"=>"Chart4",
                             "Title"=>"Motor Skills Section",
                             "Value_Color"=>array(0=>"rgba(119, 247, 119, 0.5)",
                                                  1=>"rgba(154, 145, 138, 0.5)",
                                                  2=>"rgba(154, 145, 138, 0.5)",
                                                  3=>"rgba(154, 145, 138, 0.5)",
                                                  4=>"rgba(154, 145, 138, 0.5)",
                                                  5=>"rgba(86, 104, 120, 0.5)"),
                             "Total_Value_Color"=>array(0=>"rgba(119, 247, 119, 1)",
                                                        1=>"rgba(154, 145, 138, 1)",
                                                        2=>"rgba(154, 145, 138, 1)",
                                                        3=>"rgba(154, 145, 138, 1)",
                                                        4=>"rgba(154, 145, 138, 1)",
                                                        5=>"rgba(86, 104, 120, 1)"),
                             "Value"=>array(0=>"120",
                                            1=>"40",
                                            2=>"40",
                                            3=>"40",
                                            4=>"40",
                                            5=>"0"),
                             "Total_Value"=>array(0=>"150",
                                                  1=>"100",
                                                  2=>"100",
                                                  3=>"100",
                                                  4=>"100",
                                                  5=>"220")),
                     5=>array("ID"=>"Chart5",
                             "Title"=>"Total ABLLS-R",
                             "Value_Color"=>array(0=>"rgba(119, 247, 119, 0.5)",
                                                  1=>"rgba(154, 145, 138, 0.5)",
                                                  2=>"rgba(154, 145, 138, 0.5)",
                                                  3=>"rgba(154, 145, 138, 0.5)",
                                                  4=>"rgba(154, 145, 138, 0.5)",
                                                  5=>"rgba(86, 104, 120, 0.5)"),
                             "Total_Value_Color"=>array(0=>"rgba(119, 247, 119, 1)",
                                                        1=>"rgba(154, 145, 138, 1)",
                                                        2=>"rgba(154, 145, 138, 1)",
                                                        3=>"rgba(154, 145, 138, 1)",
                                                        4=>"rgba(154, 145, 138, 1)",
                                                        5=>"rgba(86, 104, 120, 1)"),
                             "Value"=>array(0=>"50",
                                            1=>"10",
                                            2=>"10",
                                            3=>"10",
                                            4=>"10",
                                            5=>"0"),
                             "Total_Value"=>array(0=>"150",
                                                  1=>"100",
                                                  2=>"100",
                                                  3=>"100",
                                                  4=>"100",
                                                  5=>"220"))
                  );
?>
<!-- style="background-color:rgb(180,180,180);" -->
<div class="container-fluid m-0 p-0"> 
    <div class="align-items-center mt-3 mb-3">
        <span style="padding: 0 0 0 10px; border: 1px solid gray;">
            <p style="display: inline-block; width: 50px; height: 10px; border: 1px solid black; margin: 0; background-color: rgba(119, 247, 119, 0.5);"></p>
            <p style="display: inline; margin: 0 10px 0  0; padding: 0;" class="app-right-bottom-content"><?php echo $AnalysisDetails[0]["Assessment_Date"] ?></p>
            <p style="display: inline-block; width: 50px; height: 10px; border: 1px solid black; margin: 0; background-color: rgba(154, 145, 138, 0.5);"></p>
            <p style="display: inline; margin: 0 10px 0  0; padding: 0;" class="app-right-bottom-content">normative data (<?php echo $AnalysisDetails[0]["Normative_Data"] ?>)</p>
        </span>
    </div>
    <div class="">
        <canvas id="secgraphtotalscore" width="400" height="200"></canvas>
        <script>
            var ctx = document.getElementById( "secgraphtotalscore" ),
            example = new Chart(ctx, {
                // 參數設定[註1]
                type: "bar", // 圖表類型
                data: {
                    labels: [ "Red", "Green", "Blue" ], // 標題
                    datasets: [{
                        label: "# of Votes", // 標籤
                        data: [ 12, 19, 3 ], // 資料
                        backgroundColor: [ // 背景色
                        "#FF0000",
                        "#00FF00",
                        "#0000FF",
                        ],
                        borderWidth: 1 // 外框寬度
                    }]
                }
            });
        </script>

    </div>

</div>

