<div class="container mt-5 mb-5">
    <h2>Privacy Policy</h2>
    <h4 class="font-weight-bold">Overview</h4>
    <p class="text-justify ml-3">Welcome to WebABLLS 2.0. Behavior Data Systems, Inc. (“BDS”) operates a website, www.webablls.com and www.webablls.net (the “Site”), which you are currently seeking to gain access to. BDS is committed to protecting the privacy of our site users and have developed this policy to demonstrate our commitment. The WebABLLS Terms of Use, located at <a href="#">https://webablls.net/terms</a>, and this Privacy Policy govern the use of the Site and the services provided through this Site. This Privacy Policy discloses BDS’ practices regarding the collection, use, and disclosure of the information we receive through the Site. By using the Site, you consent to the data collection and use practices described below. Please read this Privacy Policy carefully as it contains important information regarding your legal rights, remedies and obligations while using the Site and/or services provided on this Site. Continued use by you of the Site constitutes your agreement to be bound by and subjected to this Privacy Policy as well as the Terms of Use. If you do not agree with or accept the terms of this Policy, the Terms of Use, or the Beta Agreement, you must not access the Site or use any services on the Site.</p>

    <h4 class="font-weight-bold">Information We Collect</h4>
    <p class="text-justify ml-3">The Site requires users to register before they may use the Site. During the course of this registration process, BDS collects certain Personal Identification Information and other user data about users and students. Our primary purpose in collecting Personal Identification Information from our users is to provide a safe, smooth, efficient and customized experience.</p>
    <p class="text-justify ml-3">As used herein, “Personal Identification Information”, is defined to include an individual’s (a) name; (b) phone number, (c) email address, (d) mailing/billing address (e) a personal identifier, such as a student id number; (f) other indirect identifiers, such as the individual’s date of birth/age, and/or gender; (g) company name and/or (h) other information that, alone or in combination, is linked or linkable to a specific student/child that would allow a reasonable person in the community, who does not have personal knowledge of the relevant circumstances, to identify the individual with reasonable certainty.</p>
    <p class="text-justify ml-3">As part of being able to use the Site and the services provided therein, users are required to provide and agree that BDS may collect the following information upon registration: legal name (first and last), e-mail address, telephone number, company name (if applicable), title or role (if applicable) and mailing address (“Contact Information”). In addition, users are also required to provide and agree that BDS may collect the following information for Student Profiles: name, student id, date of birth, and gender (“Student Information”). Once you provide BDS this Contact Information and Student Information you are not anonymous to us. If you choose to provide us with your Contact and Student Information, you consent to the transfer and storage of that information on our servers. Upon user account activation, the email address used for registration is assigned as the account user ID. A temporary password is automatically assigned. Upon first login to the Site, it is the user’s responsibility to choose a private password. BDS does not have access to any passwords for the Site.</p>
    <p class="text-justify ml-3">In addition, by registering to use the site you agree that BDS may collect billing account information, which includes billing-related contact information as well as payment, credit card, and/or tax identification number information (“Billing Information”). This information along with your Contact Information is collectively hereinafter referred to as “Personal Identification Information”. To the extent users post information on or submit information to the Site BDS may collect this information and associate it with Personal Identification Information to construct personalized user pages detailing a user's transaction activity. In addition, BDS may also share this Personal Identification Information with third party credit card companies and fulfillment companies for the sole purpose of fulfilling and processing payments for customer orders. In addition BDS may share aggregate-level user information that it has obtained from WebABLLS (such as age, gender or location) to share with third parties. The aggregate-level user information shared will not contain any Personal Identification Information and cannot be tied to any individual user.</p>

    <h4 class="font-weight-bold">How We Use the Information We Collect</h4>
    <p class="text-justify ml-3">Except as stated above and outlined below, BDS only uses your Personal Identification information for internal purposes. All Personal Identification Information beyond name, address, email address, and phone number will be used solely for BDS’s internal purposes, by employees of BDS, and/or companies providing BDS support and assistance in processing of financial transactions, fulfilling orders, and administration of the Site, as well as those companies’ employees These internal purposes include, but are not limited to: order processing and activation, processing of financial transactions, administration of the site, account maintenance, technical and site development, customer support, and/or sales’ history, billing purposes, and construction of personalized pages for each user.</p>
    <p class="text-justify ml-3">Except as outlined below, BDS sharing of Personal Identification Information with third parties will be limited to sharing that information with third party companies that assist BDS in administering the WebABLLS site (including Behavior Analysts, Inc. (“BAI”)), as well as companies that assist it in processing and fulfilling its orders. No Billing Information is collected or stored on the Site at this time.</p>
    <p class="text-justify ml-3">BDS may, however, share aggregate-level user information with third parties as outlined below. This aggregate information will not contain any Personal Identification Information and cannot be tied to any individual user.</p>
    <p class="text-justify ml-3">BDS reserves the right to use or disclose information provided as required by law or if BDS reasonably believes that the use or disclosure is necessary to protect BDS’ rights and/or comply with a judicial proceeding, court order or legal process. It is BDS’ policy to cooperate fully with any law enforcement officials or agencies in the investigation of any violation of any applicable laws. BDS reserves the right to seek civil, criminal or injunctive relief, at its sole discretion to enforce these Terms.</p>

    <h4 class="font-weight-bold">User Exchange of Information</h4>
    <p class="text-justify ml-3">As described in detail below (in the section titled “Information Sharing”), WebABLLS allows, with the proper permissions, one user to share certain student data with another WebABLLS user. In particular, if one user (“User 1”) has another user (“User 2”)’s email address, User 1 can allow User 2 to share access to one of User 1’s student profiles. A student profile will not be shared without the permission of the user who has entered that student profile. Such sharing will only be allowed only if the User has the appropriate level of authority to allow such sharing. When a student profile is shared, the amount of information that will be made available for sharing will vary depending on the level of sharing permissions authorized but may include things such as the student’s first/last name and organization name.</p>
    
    <h4 class="font-weight-bold">Your Own Access to Your Personal Identification Information</h4>
    <p class="text-justify ml-3">BDS provides its users with the ability to view, update, edit, archive, disable and/or block from use any Personal Identification Information stored on the Site. If you would like the opportunity to view, update, edit, archive, disable, and/or block from use your Personal Identification information on the Site; use the Account link to make updates or changes; or if necessary, contact your internal Organization administrator user, or email your request to support@webablls.net. To protect your privacy and security, we will take reasonable steps to verify your identity before making corrections, changes, or updates.</p>
    <p class="text-justify ml-3">Users are required to notify BDS at support@webablls.net when any relevant personal identification information has been updated, edited, and/or deleted from the Site. Relevant personal identification information includes: first name, last name, email address, and/or phone number.</p>

    <h4 class="font-weight-bold">Consent</h4>
    <p class="text-justify ml-3">By registering to use the Site and its services, you consent to the collection of the use of the Personal Identification Information described above.</p>
    
    <h4 class="font-weight-bold">Cookies</h4>
    <p class="text-justify ml-3">We use “Cookies” on the Site. These Cookies are used to enable you to move around the Site without having to reenter your password as frequently. Cookies are files that are stored by your browser on your computer's hard drive that contain information about your visits to the Site. Our cookies do not contain any Personal Identification Information and we do not associate your Personal Identification Information with any information collected through the cookies.</p>
    <p class="text-justify ml-3">You can set your browser to limit or let you know about cookies that a website places on your computer. If you set your browser to reject a cookie, some features of the Site may not work for you.</p>

    <h4 class="font-weight-bold">Retention of Collected Information</h4>
    <p class="text-justify ml-3">You may terminate the use of the Site at any time. Upon termination, the information that you previously provided to the Site will remain on the Site and available for use in connection with BDS’ terms, policies and practices.</p>

    <h4 class="font-weight-bold">This Site is Intended for Adult Users</h4>
    <p class="text-justify ml-3">The Site provides a service for adult use. Minors (individuals under the age of 18) are not eligible to use our services; and by completing the registration process, during which personal identification information is collected, each registered user verifies he or she is at least 18 years of age.</p>

    <h4 class="font-weight-bold">Other Sites</h4>
    <p class="text-justify ml-3">The Site may contain links to other websites. BDS makes no representations about, and is not responsible for, the user data collection practices and uses of such other websites.</p>

    <h4 class="font-weight-bold">Security</h4>
    <li class="text-justify ml-3">WebABLLS employs state-of-the-art security technology to assure that private records remain private.</li>
    <li class="text-justify ml-3">128-bit SSL encryption technology—Same security level used by banks and financial institutions.</li>
    <li class="text-justify ml-3">Customizable security levels.</li>
    <li class="text-justify ml-3">No page caching—All records remain secure on WebABLLS.</li>
    <li class="text-justify ml-3">[Student] Names are optional—User-defined codes can be assigned.</li>
    <li class="text-justify ml-3">Highly securable login page.</li>
    <p class="text-justify ml-3">BDS has gone to extensive lengths to ensure that all information contained in the private records will remain private. However, visitors and users must be aware and by using the Site acknowledge, that even with these security measures, there is always a possibility that personal information could be compromised due to the actions of individuals seeking methods to circumvent these security measures. If you are not comfortable risking the inadvertent disclosure of your private information, please do not use the Site.</p>

    <h4 class="font-weight-bold">Log In Information</h4>
    <p class="text-justify ml-3">The Site automatically records information a browser sends whenever a user requests login to the Site. These server logs may include information such as an Internet Protocol address, the User ID entered, the date and time of the request, and one or more cookies that may uniquely identify the browser. Any such information collected will be used only to detect and identify user login attempts/failures when login assistance is requested.</p>

    <h4 class="font-weight-bold">User Communications</h4>
    <p class="text-justify ml-3">When email or other communications are sent to support@webablls.com, support@webablls.net, or any WebABLLS Support Team member, we may retain those communications in order to process your inquiries, respond to your requests, and improve our services.</p>

    <h4 class="font-weight-bold">Customer Accounts / User Accounts</h4>
    <p class="text-justify ml-3">Each user account is activated within the Site under a unique organization or customer account. At the onset of account activation, the administrator user (or ‘owner’) of the organization or customer account—if not otherwise designated—is automatically assigned to the name and email address submitted during the order/registration process. The administrator user(s) of an account, whether an independent (single user) or group user, assumes all authority for any/all account activity within the organization or customer account, including the activation of user accounts associated with the organization as well as the management of user account role assignments (Administrator, Standard, or Restricted Each organization or customer account must have at least one administrator user, but other associate users can also be designated as additional administrator users (each of whom shares the same level of authority within the organization or customer account).</p>
    <p class="text-justify ml-3">Organization administrator users are responsible for account maintenance with regard to placing orders, creating and managing user accounts, facilitating password changes and/or resets, monitoring both user account and student profile assignments and permissions. Other responsibilities include various organization functions such as timeout settings and establishing custom student parameters.</p>
    <p class="text-justify ml-3">User accounts clustered within a single customer account are considered to have provided opt-in consent for personal identification information and organization or customer account subscription or license key history to be available to user accounts registered with an Administrator or Standard user role via the Site as well as through customer support inquiries. User accounts registered with a Restricted user role do not have access to subscription or license key history.</p>
    <p class="text-justify ml-3">Customer account and user account information is gathered by BDS at the time of registration/activation and is entered and stored within an electronic customer management system for use by only BDS and the companies that assist it in administering the site, as well companies assisting it in the processing and fulfilling of orders.</p>

    <h4 class="font-weight-bold">Information Sharing – Personal Identification Information</h4>
    <p class="text-justify ml-3">BDS only shares personal information with other Site users in the following limited circumstances:</p>
    <li class="text-justify ml-3">We have your consent. We require opt-in consent for the sharing of any user or account information.</li>
    <li class="text-justify ml-3">Opt-in consent is considered accepted for all users clustered within a specific organization or customer account including the administrator user(s), subscriber(s), and/or associate user(s).</li>
    <li class="text-justify ml-3">We provide such information to our subsidiaries, affiliated companies or other trusted business partners or persons, including but not limited to BAI and its employees, for the purpose of processing personal information, accounting and billing activities, and technical components of the Site on our behalf. BDS requires that these parties agree to process such information based on our instructions and in compliance with this Privacy Policy and any other appropriate confidentiality and security measures.</li>
    <li class="text-justify ml-3">We have a good-faith belief that access, use, preservation or disclosure of such information is reasonably necessary to (a) satisfy any applicable law, regulation, legal process or enforceable governmental request, (b) enforce applicable Terms of Service, including investigation of potential violations thereof, (c) detect, prevent, or otherwise address fraud, security or technical issues, or (d) protect against imminent harm to the rights, property or safety of BDS, the registered users of the Site, or the public as required or permitted by law.</li>
    <li class="text-justify ml-3">If the Site becomes involved in a merger, acquisition, or any form of sale of some or all of its assets, we will provide notice before personal information is transferred should it become subject to a different privacy policy.</li>
    
    <h4 class="font-weight-bold">Information Sharing – Student Records</h4>
    <h5 class="font-weight-bold">Student Records (a)</h5>
    <p class="text-justify ml-3">The Site’s function is to facilitate the hosting of student information, data, and reports (“Student Records”) via user accounts within Organizations (or customer accounts). BDS will not review, share, distribute, or reference any Student Record except as described above in the Information Sharing – Personal Identification Information section, or as may be required by law.</p>
    <p class="text-justify ml-3">Upon creation of each Student Record the Site automatically generates a unique identification number (ID#). Identification number codes associated with Student Records may be viewed or accessed only for the purpose of customer support, or account maintenance as requested by users, or suspected violation of BDS’s terms of service, or as may be required by law.</p>
    <p class="text-justify ml-3">Users are responsible for maintaining the security and confidentiality of their account details including passwords. A user’s password may not be shared with any other individual. Each user is required to have his/her own user ID and password and that password may not be shared with any other individual. Sharing of an individual’s password and/or user account compromises the Site’s security features, will constitute a violation of this privacy policy, and may result in immediate termination of the user’s access to the Site.</p>

    <h5 class="font-weight-bold">Student Records (b)</h5>
    <p class="text-justify ml-3">Users who are designated as the administrator of the organization or customer account, owner of a Student Record, or profile coordinator of a Student Record assumes responsibility for the authorization of sharing rights to other Site users who are registered with user accounts in the system. Authorization of sharing rights is not limited to only those user accounts within a corresponding organization or customer account. The procedure to authorize sharing rights provides the administrator, owner, and/or profile coordinator of the Student Record the option to grant customized sharing permissions using the following configurations:</p>
    
    <h5 class="font-weight-bold">Permissions for entire student profile (all with Modify Rights)</h5>
    <p class="text-justify ml-3">Owner Rights<br>Full Access with sharing rights<br>Full Access</p>
    <p class="text-justify ml-3">“Owner” permissions grant the authorized user access to the entire Student Record without any restrictions. The authorized user has access to modify/edit/change all associated information with regard to the Student Record, including the modification of the existing owner settings.</p>
    <p class="text-justify ml-3">“Full Access with sharing rights” permissions grant the authorized user access to the entire Student Record without any restrictions. The authorized user has access to modify/edit/change all associated information with regard to the Student Record, including the authorization of sharing rights to other site users but cannot edit the owner settings.</p>
    <p class="text-justify ml-3">“Full Access” permissions grant the authorized user access to the entire Student Record without any restrictions. The authorized user has access to modify/edit/change all associated information with regard to the Student Record, without the ability to authorize sharing rights to other site users.</p>

    <h5 class="font-weight-bold">Permissions for sections of student profile</h5>
    <p class="text-justify ml-3">Basic Info | View<br>Basic Info | Modify<br>Assessments & Reports | View<br>Assessments & Reports | Modify<br>Files | View<br>Files | Modify</p>
    <p class="text-justify ml-3">View permissions grant the authorized user access to view and/or print the specified segment of a Student Record (Basic Info, Assessment and Reports, and/or Files) from the Site. View permissions does not allow any manipulation of the Student Record specified segments(s) associated with the authorized student ID. No changes to the specified segment(s) of the Student Record associated with the authorized student ID can be made with View sharing permissions. The user granted with View permissions can elect to delete/cancel the sharing permissions’ authorization at any time.</p>
    <p class="text-justify ml-3">Modify permissions grant the authorized user access to the same access as View permissions in addition to the authorization to modify/edit/change/create within the specified segment of a Student Record (Basic Info, Assessment and Reports, and/or Files) from the Site. Modify permissions does allow the manipulation of the specified segments(s) associated with the authorized student ID. The user granted with Modify permissions can elect to delete/cancel the sharing permissions’ authorization at any time.</p>
    <p class="text-justify ml-3">Any combination of View or Modify permissions can be authorized for the three defined segments associated with a Student Record including (1) Basic Info (Student Profile), (2) Assessment and Reports, and (3) Files.</p>
    <p class="text-justify ml-3">Each Student Record is unique within the Site and authorization of sharing permissions must be authorized independently. Authorization of sharing permissions can be added/modified/deleted at any time. The Site automatically generates an email notification to the user’s registered email address upon authorization or modification of sharing permissions. No notification is generated when sharing permissions are removed.</p>

    <h5 class="font-weight-bold">Student Records (c)</h5>
    <p class="text-justify ml-3">Without limiting the above, BDS will maintain appropriate administrative, physical, and technical safeguards for protection of the security, confidentiality, and integrity of Student Records. BDS will not (a) modify Student Records, (b) disclose Student Records except as required by law, or as specifically requested/authorized in writing by the assigned owner or profile coordinator of the Student Record or the organization or customer account administrator, or (c) access a Student Record except to address technical problems, or upon request in connection with providing customer support.</p>

    <h5 class="font-weight-bold">Student Records (d)</h5>
    <p class="text-justify ml-3">Due to the sensitive nature of the confidential Student Records hosted on the Site, BDS will not provide customer support to individuals who do not have a valid user account and/or who are not registered within our customer database.</p>

    <h4 class="font-weight-bold">Changes in Policy</h4>
    <p class="text-justify ml-3">BDS reserves the right to change this Privacy Policy. BDS will provide notification of material changes to this Privacy Policy through the Site at least thirty (30) days prior to the change taking effect. Your continued use of the Site after any change in Privacy Policy will constitute your acceptance of such change.</p>

    <h4 class="font-weight-bold">How to Contact Us</h4>
    <p class="text-justify ml-3">Should you have other questions or concerns about this privacy policy, please contact us at support@webablls.net.</p>

</div>

<!--Back to top-->
<a href="#" class="back-to-top"><i class="fas fa-arrow-up fa-2x align-middle"></i></a>  