<div class="container mt-5 mb-5">
    <h2>WebABLLS™ Terms & Conditions of Use</h2>
    <p class="text-justify ml-3">Last Updated: August 7, 2015</p>
    <p class="text-justify ml-3">WebABLLS, provided through the website www.webablls.net (“WebABLLS” or the “Site”), is owned and operated by Behavior Data Systems, Inc. (“BDS” or “Us”). BDS is committed to protecting its users, including but not limited to its Beta Users, Trial Users, and Customers as defined below in Section I (collectively “You” or “Your”) privacy and developing technology that gives You the most powerful and safe online experience. The following terms of use (the “Terms”) govern the use of the Site and Services. Please read these Terms carefully, along with the <a href="{{ url('/privacy') }}">Privacy Policy</a>, as they contain important information regarding Your legal rights, remedies, and obligations while using the Site and/or Service. By using the Site and/or Service, You consent to the data practices described in this statement and agree to be bound by these Terms and Conditions of Use (the “Agreement”). <b>If You do not agree with or accept these Terms, You must not access the Site or use the Service.</b></p>

    <p class="text-justify ml-3">THIS AGREEMENT GOVERNS YOUR ACQUISITION AND USE OF BDS (“OUR”) SERVICES.</p>

    <p class="text-justify ml-3">IF YOU REGISTER FOR A FREE TRIAL FOR OUR SERVICES, THIS AGREEMENT WILL ALSO GOVERN THAT FREE TRIAL.</p>

    <p class="text-justify ml-3">BY ACCEPTING THIS AGREEMENT, EITHER BY CLICKING A BOX INDICATING YOUR ACCEPTANCE OR BY EXECUTING AN ORDER FORM THAT REFERENCES THIS AGREEMENT, YOU AGREE TO THE TERMS OF THIS AGREEMENT. IF YOU ARE ENTERING INTO THIS AGREEMENT ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THESE TERMS AND CONDITIONS, IN WHICH CASE THE TERMS "YOU" OR "YOUR" SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT AGREE WITH THESE TERMS AND CONDITIONS, YOU MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE THE SERVICES.</p>
    
    <p class="text-justify ml-3">You may not access the Services if You a direct competitor of BDS or Behavior Analysts, Inc. (“BAI”), except with BDS’ prior written consent. In addition, You may not access the Services for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.</p>

    <p class="text-justify ml-3">This Agreement was last updated on August 5, 2015. It is effective between You and BDS as of the date of You accepting this Agreement.</p>
    
    <h4 class="font-weight-bold">I. Organizations and Users</h4>
    <p class="text-justify ml-5">Certain individuals (“Persons”), representing themselves, schools, and/or companies (“Organizations”) may register to use WebABLLS in one of three manners.</p>
    <p class="text-justify ml-5">First, in order to help ensure quality of the services and Site being provided, certain Persons may be invited to use and test certain new and/or experimental versions or features of the Site for a limited period of time without having to pay any subscription fee. These users are hereinafter referred to as “Beta Users.”</p>
    <p class="text-justify ml-5">In addition, some Persons may be offered the opportunity to use all or part of the WebABLLS services on a limited basis without any subscription fee. These Persons are hereinafter referred to as “Trial Users”.</p>
    <p class="text-justify ml-5">Persons registering to use the current full functioning version of WebABLLS and to pay the full subscription, activation, and/or renewal rate, as described below, including but not limited to associate and independent users, are hereinafter referred to as a “Customers”.</p>
    <p class="text-justify ml-5">Beta Users, Trial Users and Customers are hereinafter collectively referred to as “Users,” “You” or “Your.”</p>

    <h4 class="font-weight-bold">II. Acceptance of Terms of Use</h4>
    <p class="text-justify ml-5">These Terms govern Your use of the WebABLLS Site and the services provided therein, including all features, functionalities, content, website, and software associated therewith (the “WebABLLS Service”). By using, testing, and/or visiting the WebABLLS Service You accept and agree to be bound by these Terms. If You do not agree to accept these Terms, You should not use the WebABLLS Service, including the WebABLLS website and user interfaces.</p>
    <p class="text-justify ml-5">These Terms are an ongoing contract between You and BDS and apply to Your use of the WebABLLS Service as made available to You. They affect Your rights and You should read them carefully.</p>
    <p class="text-justify ml-5">These Terms apply to all Users (including Beta Users, Trial Users, and Customers) as defined above.</p>

    <h4 class="font-weight-bold">III. Privacy and Communications Preferences</h4>
    <p class="text-justify ml-5">Any personally identifying information submitted through the WebABLLS service is subject to our Privacy Policy, the terms of which are incorporated herein. Please review our Privacy Policy to understand our practices.</p>

    <h4 class="font-weight-bold">IV. Service</h4>
    <p class="text-justify ml-5">The WebABLLS Service and Site is the online assessment, curriculum guide, and skills tracking system that mirrors the ABLLS-R® in an electronic format. WebABLLS offers electronic features that enable the user to track intervention programs via the WebABLLS Internet platform in addition to being able to generate Program Worksheets, progress reports and other reporting-type features. WebABLLS also enables users to authorize sharing rights among other program team members.</p>

    <h4 class="font-weight-bold">V. License and Site Access</h4>
    <p class="text-justify ml-5">Subject to the terms and conditions of this agreement, BDS grants Customers and Trial Users a limited, non-exclusive, non-transferable license (without the right to sub-license) to access and make personal use of the Site and the software contained therein, including any relevant software updates, during the Customers’ Subscription Period, but not to download or modify it, or any portion of it, except with the express written consent of BDS. This license does not include any resale or commercial use of the Site or the software contained therein.</p>
    <p class="text-justify ml-5">Notwithstanding any of the foregoing, Customers’ subscription provides Customers an electronic copy of the ABLLS-R® Scoring Instructions and IEP Development Guide along with the authority to produce a personalized WebABLLS version of the protocol in a PDF format for exclusive use with the particular student.</p>
    <p class="text-justify ml-5">The WebABLLS Service is licensed on a per student/seat basis and thus Customers’ license to use the contents of this service is limited to the use of WebABLLS for the number of students/seats identified and paid for upon registration and shall not be used for any additional students (reuse of a seat is permitted following the purge or archive of a student).</p>
    <p class="text-justify ml-5">Subject to the terms and conditions of this agreement, BDS grants Beta Users a non-exclusive, non-transferable license (without the right to sub-license) to use the WebABLLS Site and software and services contained therein solely for the purpose of internal testing and evaluation.</p>

    <h4 class="font-weight-bold">VI. Restrictions on Grant</h4>
    <p class="text-justify ml-5">Except as otherwise specifically permitted in this Agreement, you may not: (a) modify or create any derivative works of any WebABLLS software, content, or documentation, including translation or localization; (code written to published APIs (application programming interfaces) for the WebABLLS Software shall not be deemed derivative works); (b) copy the WebABLLS software except as provided in this Agreement or elsewhere by BDS (c) separate software, which is licensed as a single product, into its component parts. (d) sub-license or permit simultaneous use of the software by more than one user; (e) reverse engineer, decompile, or disassemble or otherwise attempt to derive the source code for the WebABLLS software (except to the extent applicable laws specifically prohibit such restriction); (f) redistribute, encumber, sell, rent, lease, sub-license, use the WebABLLS software in a timesharing or service bureau arrangement, or otherwise transfer rights to any Software. You may NOT transfer the WebABLLS Software under any circumstances; (g) remove or alter any trademark, logo, copyright or other proprietary notices, legends, symbols or labels in the software or on the Site, (h) publish any results of benchmark tests run on any WebABLLS software to a third party without BDS prior written consent; or (i) use the WebABLLS software for any additional students beyond the number licensed.</p>
 
    <h4 class="font-weight-bold">VII. Your Account</h4>
    <p class="text-justify ml-5">If You use the Site, You are responsible for maintaining the confidentiality of Your account and password and for restricting access to Your computer, and You agree to accept responsibility for all activities that occur under Your account or password. BDS does provide services for children, but it sells them to adults, who can purchase those services with a credit card or other permitted payment method.</p>

    <h4 class="font-weight-bold">VII. Subscriptions and Billing</h4>    
    <h5 class="font-weight-bold ml-5">Subscription Price</h5>
    <h6 class="ml-5">Customers</h6>
    <p class="text-justify ml-5">The subscription price and license granted is on a per student basis. The price of the subscription for the first year is $100.00 per student profile/seat ($40.00 activation fee + $60.00 annual rate) (the “Initial Rate”), with a renewal rate of $60.00 per student (“Renewal Rate”).</p>
    <p class="text-justify ml-5">From time to time in certain special circumstances, BDS may choose to waive the first-year fee and offer a Customer a complimentary subscription for their first year of use without any charge. In such circumstances, any subsequent subscription by that Person will be charged at the Renewal Rate. For all other purposes other than billing, such Persons will be treated as a Customer.</p>
    <h6 class="ml-5">Trial Users</h6>
    <p class="text-justify ml-5">Certain other persons may be offered a subscription on a trial basis (“Trial Users”). If you begin your use of the WebABLLS service as a Trial User you will not be charged for the first month of use the service, or for a period otherwise specified during registration (the “Trial Period”). Your WebABLLS Trial Period will begin when you register for use of the Site. Upon expiration of your trial membership you will be eligible to sign up for a regular subscription at the Initial Rate as described above.</p>
    <h6 class="ml-5">Beta Users</h6>
    <p class="text-justify ml-5">If you are using the WebABLLS service as a Beta User you will not be billed for any subscription fee as long as you fulfill your obligations as a Beta Users. Upon completion of your service as a Beta Tester you may then sign up as a customer pursuant to the terms and subscription price set forth above.</p>
    <p class="text-justify ml-5">These prices and terms are subject to change by BDS without any prior notice except that any price change shall not apply retroactively to subscriptions that have already been purchased.</p>

    <h4 class="font-weight-bold">VIII. Subscriptions and Billing</h4>
    <h6 class="ml-5">Subscriptions</h6>
    <p class="text-justify ml-5">Unless otherwise provided in the applicable Order Summary, (a) WebABLLS Services are purchased as subscriptions, (b) subscriptions may be added during a subscription term at the same pricing as the underlying subscription pricing, prorated for the portion of that subscription term remaining at the time the subscriptions are added, and (c) any added subscriptions will terminate on the same date as the underlying subscriptions.</p>

    <h6 class="ml-5">Fees</h6>
    <p class="text-justify ml-5">WebABLLS fees are specified above and available within the Order Portal of www.webablls.net. Except as otherwise specified, (i) fees are based on the subscriptions purchased and not actual usage, (ii) payment obligations fees paid are non-refundable past 30 days, and (iii) quantities purchased cannot be decreased during the relevant subscription term.</p>

    <h6 class="ml-5">Invoicing and Payment</h6>
    <p class="text-justify ml-5">You will provide Us with valid credit card information, or with a valid purchase order or alternative document reasonably acceptable to Us. If You provide credit card information to Us, You authorize Us to charge such credit card for all Purchased subscriptions listed in the Order Summary for the initial subscription term and any renewal subscription term(s).</p>
    <p class="text-justify ml-5">Such charges shall be made in advance. If the Order specifies that payment will be by a method other than a credit card, We will invoice You in advance and otherwise in accordance with the relevant Order Summary. Unless otherwise stated in the Order, invoiced charges are due net 30 days from the invoice date. You are responsible for providing complete and accurate billing and contact information to Us and notifying Us of any changes to such information.</p>

    <h4 class="font-weight-bold">IX. Beta Product Disclaimer</h4>
    <p class="text-justify ml-5">The Beta product and service bring provided to Beta Users is believed to contain defects and a primary purpose of the license being granted to Beta Users is to obtain feedback on the performance of WebABLLS and the identification of defects. Beta Users are advised to safeguard important data, to use caution and not to rely in any way on the correct functioning or performance of the WebABLLS version they are being provided.</p>

    <h4 class="font-weight-bold">X. Beta User Feedback</h4>
    <p class="text-justify ml-5">It is expressly understood, acknowledged and agreed that Beta Users shall, regardless of whether or not formally requested to do, provide to BDS reasonable suggestions, comments and feedback regarding the WebABLLS service, including but not limited to reports of usability, feature benefits and downfalls, and bug reports (the “Feedback”). If you provide such Feedback to BDS, you shall grant BDS the following worldwide, non-exclusive, perpetual, irrevocable, royalty free, assignable fully paid up rights: (i) to make, use, copy, modify, sell, distribute, sub-license, and create derivative works of, the Feedback as part of any BDS or BAI product, technology, service, specification or other documentation ; (ii) to publicly perform or display, import, broadcast, transmit, distribute, license, offer to sell, and sell, rent, lease or lend copies of the Feedback (and derivative works thereof) as part of any BDS or BAI Product; (iii) solely with respect to the Beta User’s copyright and trade secret rights, to sub-license to third parties the foregoing rights, including the right to sub-license to further third parties; and (iv) to sub-license to third parties any claims of any patents owned or licensable by the Beta User that are necessarily infringed by a third party product, technology or service that uses, interfaces, interoperates or communicates with the feedback or portion thereof incorporated into a BDS or BAI Product, technology or service. Further, you warrant that your Feedback is not subject to any license terms that would purport to require BDS or BAI to comply with any additional obligations with respect to any BDS or BAI Products that incorporate any Feedback.</p>

    <h4 class="font-weight-bold">XI. Beta-Software Product Support</h4>
    <p class="text-justify ml-5">BDS is under no obligation to provide technical support to Beta Users under the terms of this license, and provides no assurance any specific errors or discrepancies in WebABLLS will be corrected. Provision of any software or services to Beta Users under this Agreement is experimental and shall not create any obligation for BDS to continue to develop, productize, support, repair, offer for sale or in any other way continue to provide or develop software or services either to Beta Users or to any other party.</p>

    <h4 class="font-weight-bold">XII. Trial User Limitations</h4>
    <p class="text-justify ml-5">As part of their trial subscription, Trial Users’ access to certain function and/or features may be limited by BDS. The specific limitations applicable to a trial user will be determined on a case-by-case basis and will be provided to Trial Users when they are first offered their trial subscription.</p>

    <h4 class="font-weight-bold">XIII. Customer Returns and Cancellation</h4>
    <h5 class="font-weight-bold ml-5">Returns</h5>
    <p class="text-justify ml-5">Behavior Analysts, Inc., offers a 30-day return policy for WebABLLS subscriptions. To process a return, please contact the WebABLLS Support Team via the contact page within 30 days of account activation. You will be charged a $50 processing fee and the remaining balance will be refunded consistent with the original mode of payment.</p>
    <h5 class="font-weight-bold ml-5">Cancellations</h5>
    <p class="text-justify ml-5">You may cancel Your subscription to WebABLLS at any time and cancellation will be effective immediately. BDS does not provide refunds or credits for any partial month membership periods. To cancel an email stating such cancellation should be sent to support@webablls.net.</p>

    <h4 class="font-weight-bold">XIV. BDS Right to Terminate and/or Restrict Use</h4>
    <p class="text-justify ml-5">BDS reserves the right to terminate or restrict Your use of the WebABLLS service without notice or for any reason whatsoever, at any time.</p>

    <h4 class="font-weight-bold">XV. Copyright & Trademark</h4>
    <p class="text-justify ml-5">All content and software included on the Site, including but not limited to text, graphics, logos, button icons, images, video clips, audio clips, digital downloads, data compilations and software, is the property of BDS or BAI. ABLLS® is the registered trademark of Behavior Analysts, Inc. in the United States and other countries, and WebABLLS is the trademark of BDS.</p>

    <h4 class="font-weight-bold">XVI. Limitations on Use</h4>
    <p class="text-justify ml-5">You must be 18 years of age or older to become a member of the WebABLLS service. In certain jurisdictions, the age of majority may be older than 18, in which case You must satisfy that age in order to become a member. Any unauthorized use of the WebABLLS Site or its contents will immediately terminate the limited license granted by us and will result in the cancellation of Your membership.</p>

    <h4 class="font-weight-bold">XVII. Not Medical Advice</h4>
    <p class="text-justify ml-5">The information provided on this Site is for educational and entertainment purposes only and should not be interpreted as a recommendation for a specific treatment plan, service, or course of action. Neither BDS nor BAI is providing specific medical advice through this Site, is not engaged in providing medical or professional services and does not endorse any medical or professional service obtained through information provided on this Site or any links to this Site. Use of the Site does not replace medical consultations with a qualified health or medical professional to meet the health and medical needs of you or a loved one. You exercise your own judgment when purchasing any product or service through the Site.</p>

    <h4 class="font-weight-bold">XVIII. Confidentiality</h4>
    <p class="text-justify ml-5">You agree not to disclose BDS Confidential Information without BDS's prior written consent. “BDS Confidential Information" includes, but is not limited to: (a) all BDS software, technology, programming, specifications, materials, guidelines and documentation relating to the WebABLLS Service; (b) any other information designated by BDS as "Confidential" or an equivalent designation. BDS Confidential Information does not include (i) information that has become publicly known through no breach of obligations of confidentiality by You or any third party; (ii) non-confidential information that has been rightfully received by You from a third party; or (iii) information that You are required to disclose by law or by a governmental authority, but only to the extent of such requirement.</p>

    <h4 class="font-weight-bold">XIX. Security</h4>
    <p class="text-justify ml-5">Our web hosting and other services providers use lots of tools to protect Your personal information against unauthorized access and disclosure, including encryption, passwords and physical security. However, as You probably know, no data storage facility can be made completely secure, and third parties may unlawfully access data or intercept transmissions or private communications. Therefore, although we try very hard to protect Your privacy, we do not promise, and You should not expect, that Your personal information or private communications will always remain secure and private. If You are not comfortable risking the inadvertent disclosure of Your private information, please do not post it on the Site or Service.</p>

    <h4 class="font-weight-bold">XX. Availability of the WebABLLS Service</h4>
    <p class="text-justify ml-5">BDS intends the WebABLLS Service to be available 24 hours a day, 7 days a week, except for scheduled maintenance periods; however BDS makes no assurances or promises that the Service or Site will be available as intended. BDS shall not be liable for losses related to the inability to access the Site or Service due to disruptions.</p>

    <h4 class="font-weight-bold">XXI. Disclaimers of Warranties and Limitation of Liability</h4>
    <p class="text-justify ml-5">This site and all information, content, materials, products (including software) and services included on or otherwise made available to You through this site are provided by BDS on an "as is" and "as available" basis, unless otherwise specified in writing. BDS makes no representations or warranties of any kind, express or implied, as to the operation of this site or the information, content, materials, products (including software) or services included on or otherwise made available to You through this site, unless otherwise specified in writing. You expressly agree that Your use of this site is at Your sole risk.</p>
    <p class="text-justify ml-5">To the full extent permissible by applicable law, BDS disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. BDS does not warrant that this site; information, content, materials, products (including software) or services included on or otherwise made available to You through this site; their servers; or electronic communications sent from BDS are free of viruses or other harmful components Neither BDS nor BAI shall be liable for any damages of any kind arising from the use of this site or from any information, content, materials, products (including software) or services included on or otherwise made available to You through this site, including, but not limited to direct, indirect, incidental, punitive, and consequential damages, unless otherwise specified in writing.</p>
    <p class="text-justify ml-5">Certain state laws do not allow limitations on implied warranties or the exclusion or limitation of certain damages. If these laws apply to you, some or all of the above disclaimers, exclusions, or limitations may not apply to you, and You might have additional rights.</p>
    <p class="text-justify ml-5">BDS’ and BAI’s cumulative liability to YOU or any party related to you for any loss or damage arising from or out of or relating to this Agreement or use of the WebABLLS services and/or content shall not exceed the amount of license fees paid to BDS by You under this Agreement. This limitation applies to all causes of action or claims in the aggregate, including without limitation, breach of contract, breach of warranty, indemnity, negligent, strict liability, misrepresentation, and other torts. In no event shall BDS or BAI be liable to You or any party related to You for any indirect, incidental consequential, special, exemplary, or punitive damages or lost profits, even if BDS and/or BAI has been advised of the possibility of such damages.</p>

    <h4 class="font-weight-bold">XXII. Indemnification</h4>
    <p class="text-justify ml-5">You agree to indemnify BDS, BAI, their affiliates, directors, employees, agents, representatives and third party service providers, and to defend and hold each of them harmless, from any and all claims, actions, liabilities, damages, and costs (including attorneys’ fees) (collectively, “Claims”) which may arise from: (i) Your misuse of Your BDS account; (ii) Your unauthorized use of the Site or Service; (iii) Your breach of these Terms; or (iv) any claims of infringement or violation of any third party’s intellectual property rights or privacy rights. BDS shall provide prompt written notice of such Claims and shall provide proper and full information and reasonable assistance to the indemnitor for the defense and/or settlement any such Claims. BDS reserves the right to assume the exclusive control of any such defense of any such Claim.</p>

    <h4 class="font-weight-bold">XXIII. Dispute Resolution and Governing Law</h4>
    <p class="text-justify ml-5">These Terms and Conditions of Use shall be governed by, and interpreted and enforced in accordance with, the laws of the state of California as well as any applicable federal intellectual property law. Any claim, dispute or controversy shall be brought before the competent courts of California, either federal court or state court in Contra Costa County, and the parties consent to the jurisdiction and venue in such courts. This provision shall survive the termination of Your right to use this Site.</p>

    <h4 class="font-weight-bold">XXIV. Changes to Terms of Use</h4>
    <p class="text-justify ml-5">BDS reserves the right, from time to time, with or without notice to you, to change these Terms of use in its sole and absolute discretion. If any of the conditions contained within these Terms shall be deemed invalid, void or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition.</p>

    <h4 class="font-weight-bold">XXV. Entire Agreement</h4>
    <p class="text-justify ml-5">This Agreement along with the privacy policy referenced herein, constitutes the complete and exclusive agreement between You and BDS with respect to the subject matter hereof, and supersedes all prior or contemporaneous oral or written communications, proposals, representations, understandings, or agreements not specifically incorporated herein. This Agreement may not be amended except in a writing duly signed by you and an authorized representative of BDS.</p>

    <h4 class="font-weight-bold">XXVI. Our Address</h4>
    <p class="text-justify ml-5">Behavior Analysts, Inc.<br>3478 Buskirk Avenue, Suite 1000<br>Pleasant Hill, CA 94523<br>USA<br>925-210-9370</p>

</div>

<!--Back to top-->
<a href="#" class="back-to-top"><i class="fas fa-arrow-up fa-2x align-middle"></i></a>  